config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from edscc.core.views import (
    galnet_news,
    galnet_news_detail,
    home_page,
    login_required_alert,
    placeholder,
    privacy_policy,
    sync_galnet_news,
    install_setup,
)
from edscc.commander import urls as commander_urls
from edscc.squadron import urls as squadron_urls

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path("admin/sync/galnet_news/", sync_galnet_news, name="sync-galnet-news"),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", home_page, name="home"),
    path("install-setup/", install_setup, name="install-setup"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("galnet/", galnet_news, name="galnet"),
    path("galnet/<slug:slug>", galnet_news_detail, name="galnet-detail"),
    path("blog/", placeholder, name="blog"),
    path("github/", placeholder, name="github"),
    path("patreon/", placeholder, name="patreon"),
    path("discord/", placeholder, name="discord"),
    path("placeholder/", placeholder, name="placeholder"),
    path("privacy_policy/", privacy_policy, name="privacy-policy"),
    path("commander/", include(commander_urls, namespace="commander")),
    path("squadron/", include(squadron_urls, namespace="squadron")),
    path("login_required/", login_required_alert, name="login-required"),
    path("martor/", include("martor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("edscc.api.urls")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

edscc/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"groups", views.GroupViewSet)
# router.register(r'commander', views.CommanderViewSet)


# Wire up API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path("", include(router.urls)),
    path("commander/<int:pk>", views.commander_detail, name="commander_detail"),
    path("auth/", include("rest_framework.urls", namespace="rest_framework")),
]

edscc/commander/urls.py
from django.urls import path

from edscc.core.views import placeholder, cmdr_fleet_carrier, sync_fleet_carrier

from .views import (
    about_commander,
    dashboard,
    game_journal,
    game_journal_upload,
    initial_setup,
    activities_report,
    chart_js_generator,
)
from .chart_views import CommanderDashboardLineChart, CommanderDashboardPieChart
from .ajax_datatables import AjaxJournalLog

app_name = "commander"

urlpatterns = [
    path(
        "datatable/report/commander/<slug:report>/",
        activities_report,
        name="ajax_activities_report",
    ),
    path("activities_report/", activities_report, name="activities_report"),
    path(
        "chart/line/<slug:report_id>/",
        CommanderDashboardLineChart.as_view(),
        name="commander_line_chart",
    ),
    path(
        "chart/pie/<slug:report_id>/",
        CommanderDashboardPieChart.as_view(),
        name="commander_pie_chart",
    ),
    path(
        "chart/js/<slug:report_id>/chart.js",
        chart_js_generator,
        name="chart_js_generator",
    ),
    path("dashboard/", dashboard, name="dashboard"),
    path("datatable/journal_log", AjaxJournalLog.as_view(), name="ajax_journal_log"),
    path("fleet_carrier/", cmdr_fleet_carrier, name="fleet_carrier"),
    path("game_journal/", game_journal, name="game_journal"),
    path("game_journal/upload/", game_journal_upload, name="game_journal_upload"),
    path("initial_setup/", initial_setup, name="initial_setup"),
    path("profile/", about_commander, name="profile"),
    path("sync_fleet_carrier/", sync_fleet_carrier, name="sync_fleet_carrier"),
]

edscc/squadron/urls.py
from django.urls import path

from edscc.core.views import placeholder, cmdr_fleet_carrier, sync_fleet_carrier

from .views import (
    join_squadron,
    setup_squadron,
    finish_activate_squadron,
    settings,
    roster,
    leaderboard,
)

from .ajax_datatables import AjaxMemberRoster

app_name = "squadron"

urlpatterns = [
    path("join_squadron/", join_squadron, name="join_squadron"),
    path("setup_squadron/", setup_squadron, name="setup_squadron"),
    path(
        "finish_activate_squadron/",
        finish_activate_squadron,
        name="finish_activate_squadron",
    ),
    path("settings/", settings, name="settings"),
    path("roster/", roster, name="roster"),
    path("datatable/roster/", AjaxMemberRoster.as_view(), name="roster_datatable"),
    path("leaderboard/", leaderboard, name="leaderboard"),
]

edscc/api/models.py
# from django.db import models

# Create your models here.

edscc/commander/forms.py
from django import forms

from .models import JournalLog


class JournalLogForm(forms.ModelForm):
    class Meta:
        model = JournalLog
        fields = ("file",)

edscc/squadron/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Squadron


class SquadronForm(forms.ModelForm):

    home_base = forms.CharField(
        max_length=50,
        label=_("Home Base"),
        help_text=_(
            "Location of Squadron's home base, include the System and base name. (e.g. Sol - Abraham Lincoln)"
        ),
    )

    primary_language = forms.ChoiceField(
        label=_("Primary Language"),
        choices=Squadron.LANGUAGE_CHOICES,
        required=True,
        help_text=_(
            "Primary language of this Squadron used for announcements, messaging, etc."
        ),
    )

    description = forms.CharField(
        label=_("Description"),
        widget=forms.Textarea(attrs={"rows": 4}),
        help_text=_("Write short description about your Squadron"),
        required=False,
    )

    welcome_message = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4}),
        help_text=_(
            "The welcome message will be shown to commanders after logging in the system for the first time. (Use Markdown for formatting)"
        ),
        required=False,
    )

    require_approval = forms.BooleanField(
        label=_(
            "Require approval from squad leaders to associate their accounts to this Squadron on ED:SCC"
        )
    )

    uuid = forms.UUIDField(
        widget=forms.HiddenInput(),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "squadron_form"
        self.helper.form_class = "form-text"
        self.helper.form_method = "post"
        # self.helper.layout = Layout(
        #     Field("uuid", type="hidden"),
        # )

    class Meta:
        model = Squadron
        fields = (
            "home_base",
            "primary_language",
            "description",
            "welcome_message",
            "require_approval",
            "uuid",
        )

edscc/api/views.py
import logging

from django.contrib.auth.models import Group, User
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from edscc.commander.models import Commander

from .serializers import GroupSerializer, UserSerializer

# Create your views here.

log = logging.getLogger(__name__)


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = User.objects.all().order_by("-date_joined")
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """

    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = (IsAuthenticated,)


# class CommanderViewSet(viewsets.ModelViewSet):
#     queryset = Commander.objects.all()
#     serializer_class = CommanderSerializer
#     permission_classes = [IsAuthenticated]


@api_view(["GET"])
def commander_detail(request, pk):
    log.debug(request.user)
    log.debug(request.auth)

    content = {"commander": JSONRenderer().render(Commander.objects.filter(user_id=pk))}
    return Response(content)


# class HelloView(APIView):
#     permission_classes = [IsAuthenticated]
#
#     def get(self, request):
#         log.debug(request.user)
#         log.debug(request.auth)
#         content = {
#             'message': 'Hello world!'
#         }
#         return Response(content)

edscc/commander/views.py
import logging
import os
import time
import traceback

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, HttpResponseNotFound, JsonResponse
from django.shortcuts import redirect, render, resolve_url
from django.template.defaultfilters import filesizeformat
from django.utils.translation import gettext as _
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import ensure_csrf_cookie

from ..core.session_tracker import SessionTrackerManager
from ..core.utils import evaluate_journal_log, merge_dicts
from .ajax_datatables import activities_report_callable, activities_report_title
from .chart_views import DashboardLineReports, DashboardPieReports
from .forms import JournalLogForm
from .models import CommanderInfo, UserProfile
from .tasks import parse_journal_file

log = logging.getLogger(__name__)


def index(request):
    return render(request, "placeholder.html", context={"hello": "Hello World!"})


@login_required
def about_commander(request):
    tags_ignored = ["FLEETCARRIER", "timestamp", "event"]
    info = CommanderInfo.objects.filter(user_id=request.user.id)
    data = {}

    for value in info:
        sort_list = sorted(value.content.items())
        data[value.event.lower()] = dict(sort_list)

    if "statistics" in data:
        for tag in tags_ignored:
            data["statistics"].pop(tag, None)
        data["num_categories_column"] = round((len(data["statistics"]) / 3) + 0.4)

    return render(request, "commander/commander_profile2.html", context=data)


@login_required
def initial_setup(request):
    user_list = None
    try:
        user_list = UserProfile.objects.get(id=request.user.id, is_setup_complete=True)
    except Exception as e:
        log.debug("initial_setup: %s" % e)
        traceback.print_exc()
    if user_list is None:
        return render(
            request, "commander/initial_setup.html", context={"user_list": user_list}
        )
    else:
        log.debug(user_list)
        return redirect(resolve_url("home"))


@ensure_csrf_cookie
@login_required
def activities_report(request, report=None):
    if report in activities_report_callable:
        log.debug("is executing activities report callable")
        callable_class = activities_report_callable[report]
        return callable_class.as_view()(request)
    else:
        report_name = (
            request.POST.get("selected-report")
            if request.POST.get("selected-report")
            else "earning_history"
        )

    data = {
        "available_reports": activities_report_title,
        "report_name": report_name,
    }
    return render(request, "commander/activities_report.html", context=data)


@login_required
def game_journal(request):
    data = {}
    return render(request, "commander/journal_log.html", context=data)


@login_required
def game_journal_upload(request):
    data = {"is_valid": False, "message": _("Bad method")}
    if request.method == "POST":
        form = JournalLogForm(request.POST, request.FILES)
        if form.is_valid():
            status = "Accepted"
            journal_file = form.save(commit=False)
            journal_file.user = request.user
            journal_file.save()
            file_path = settings.MEDIA_ROOT + "/" + str(journal_file.file.name)
            i = 10
            while i > 0:
                if os.path.isfile(file_path) is False:
                    i -= 1
                    if i == 0:
                        data = {"is_valid": False, "message": _("Upload failed")}
                        return JsonResponse(data)
                    time.sleep(0.5)
                else:
                    break

            filesize = filesizeformat(os.path.getsize(file_path))
            rs = evaluate_journal_log(request.user.id, file_path)

            data = {
                "is_valid": True,
                "name": str(journal_file.file.name).replace("journal_log/", ""),
                "file_type": rs["file_type"],
                "size": filesize,
                "message": _(status),
            }
            if rs["is_valid"]:
                journal_file.file_hash = rs["md5_hash"]
                journal_file.game_start = rs["game_start"]
                journal_file.game_end = rs["game_end"]
                journal_file.save()
                session = SessionTrackerManager(
                    user=request.user,
                    session_identifier="upload",
                    initial_payload={"celery_task": False},
                )
                celery_task = session.get_attr("celery_task")
                if celery_task is False:
                    parse_journal_file.apply_async(args=[request.user.id], countdown=20)
                    session.set_attr("celery_task", True)
            else:
                data["is_valid"] = False
                data["message"] = "%s: %s" % (_("Rejected"), _(rs["message"]))
                try:
                    os.remove(file_path)
                    journal_file.delete()
                    log.debug(
                        "Not valid: Upload record deleted and the file was removed"
                    )
                except FileNotFoundError:
                    pass
        else:
            data = {"is_valid": False, "message": _("Problems with the upload")}
    return JsonResponse(data)


@login_required
def dashboard(request):
    data = {
        "line_charts": DashboardLineReports().all_reports(),
        "pie_charts": DashboardPieReports().all_reports(),
    }
    return render(request, "commander/dashboard.html", context=data)


@login_required
@cache_page(300)
def chart_js_generator(request, *args, **kwargs):
    reports = merge_dicts(
        DashboardLineReports().all_reports(),
        DashboardPieReports().all_reports(),
    )
    # log.debug("reports=%s" % reports)
    if "report_id" in kwargs:
        rs = reports[kwargs["report_id"]]
        if not rs:
            return HttpResponseNotFound(kwargs["report_id"])
    else:
        return HttpResponseBadRequest

    template = "core/%s" % rs["js"]
    # log.debug("context=%s" % rs)
    return render(request, template, context=rs, content_type="text/javascript")

edscc/templates/commander/activities_report.html
{% extends 'base.html' %}
{% load i18n gravatar account humanize static %}
{% block css %}
    {{ block.super }}
    {#    <link rel="stylesheet" href="{% static 'ajax_datatable/css/style.css' %}">#}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-outline card-orange clearfix">
                        <span class="h5 text-orange">
                            <i class="fas fa-chart-line mr-1"></i>
                        {% blocktrans with cmdr=user_profile.commander_name %}
                            Activities Report for Commander {{ cmdr }}
                        {% endblocktrans %}
                        </span>
                        <div class="float-right">
                            <div class="p-0 m-0">
                                <form class="input-group-sm" method="post" href="{% url 'commander:activities_report' %}">
                                    <fieldset>
                                        <label class="mr-1">{% trans 'Select Report' %}:</label>
                                        <select id="report-picker" class="form-control text-sm" name="selected-report"
                                                style="width: 320px;">
                                            {% for key, value in available_reports.items|dictsort:1 %}
                                                <option value="{{ key }}"
                                                        {% if key == report_name %} selected="selected"{% endif %}>{% trans value %}</option>
                                            {% endfor %}
                                        </select>
                                        {% csrf_token %}
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-0">
                        <div class="table-responsive">
                            <table id="activities-report" class="table table-sm table-dark table-striped table-hover table-condensed nowrap" style="width: 100%"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(() => {
            AjaxDatatableViewUtils.initialize_table(
                $('#activities-report'),
                "{% url 'commander:ajax_activities_report' report_name %}",
                {
                    processing: true,
                    serverSide: true,
                    autoWidth: false,
                    scrollX: false,
                    dom: "<'row'<'col-sm-3'i>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-3'l><'col-sm-9'p>>",
                    language: {
                        search: '_INPUT_',
                        searchPlaceholder: '{% trans "Search..." %}',
                        info: "{% trans "datatable_info" %}",
                        infoEmpty: "{% trans "datatable_info_empty" %}",
                        infoFiltered: "{% trans "datatable_info_filtered" %}",
                        zeroRecords: "{% trans "datatable_zero_records" %}",
                        emptyTable: "{% trans "datatable_empty_table" %}",
                        paginate: {
                            first: '&laquo;',
                            previous: '&lsaquo;',
                            next: '&rsaquo;',
                            last: '&raquo;'
                        }
                    },
                    initComplete: function () {
                        $('.dataTables_filter input[type="search"]').css({
                            width: '200px', display: 'inline-block'
                        });
                    },
                    drawCallback: function () {
                        $('.dataTables_paginate > .pagination').addClass('pagination-sm');
                    }
                }, {
                },
            );
        });

        $('#report-picker').selectmenu({
            width: 325,
            change: function (event, ui) {
                this.form.submit()
            }
        });
    </script>
{% endblock %}

edscc/templates/commander/dashboard.html
{% extends 'base.html' %}
{% load i18n gravatar account humanize static %}
{% get_current_language as LANGUAGE_CODE %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row ml-1">
            <div class="col-md-12">
                <div class="card shadow">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <div id="reportrange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
                                    <i class="fa fa-calendar"></i>&nbsp;
                                    <span></span> <i class="fa fa-caret-down"></i>
                                </div>
                            </div>
                            <div class="col-md-3">
                                Cell 2
                            </div>
                            <div class="col-md-3">
                                Cell 3
                            </div>
                            <div class="col-md-3">
                                Cell 4
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row ml-1">
                    {% for key, row in pie_charts.items %}
                        {% if forloop.counter0|divisibleby:4 %}
                            {% if forloop.counter0 %}</div>
                                <div class="row ml-1">{% endif %}
                        {% endif %}
                    <div class="col-md-3">
                        <div class="card shadow">
                            <h5 class="card-header">
                                <i class="{{ row.icon }} mr-2"></i>{% trans row.title %}
                            </h5>
                            <div class="card-body">
                                <div class="chart-container" style="position: relative;">
                                    <canvas id="{{ row.chart_id }}"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% for key, row in line_charts.items %}
                    <div class="row ml-1">
                        <div class="col-md-12">
                            <div class="card shadow">
                                <h5 class="card-header">
                                    <i class="{{ row.icon }} mr-2"></i>{% trans row.title %}
                                </h5>
                                <div class="card-body">
                                    <canvas id="{{ row.chart_id }}" style="height: 30vh; width: 100%"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript">
        $(function () {

            var start = moment().subtract(29, 'days');
            var end = moment();

            function cb(start, end) {
                $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            }

            $('#reportrange').daterangepicker({
                startDate: start,
                endDate: end,
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                }
            }, cb);

            cb(start, end);

        });
    </script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js" integrity="sha512-VCHVc5miKoln972iJPvkQrUYYq7XpxXzvqNfiul1H4aZDwGBGC0lq373KNleaB2LpnC2a/iNfE5zoRYmB4TRDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% for key, row in pie_charts.items %}
        <script type="text/javascript" src="{% url "commander:chart_js_generator" key %}"></script>
    {% endfor %}
    {% for key, row in line_charts.items %}
        <script type="text/javascript" src="{% url "commander:chart_js_generator" key %}"></script>
    {% endfor %}
{% endblock %}

edscc/templates/commander/initial_setup.html
{% extends 'simple_base.html' %}
{% load i18n %}
{% block class %} dark-mode login-page{% endblock %}
{% block body %}
    <div class="login-box" style="width: 600px;">
        <div class="content">
            <!-- Commander box -->
            <div class="card card-orange shadow" style="height: 400px;">
                <div class="card-header text-center">
                    <h1 class="h1"><i class="nav-icon fas fa-user-astronaut"></i> &nbsp;{% trans 'Setting up your account' %}
                    </h1>
                </div>
                <div class="card-body">
                    <div class="overlay-wrapper">
                        <p>{% blocktrans %}
                        Hello Commander, welcome to the Squadron Command Center. Because it is your first time logging into this site, please wait while your account is being created and populated with the data from Frontier Development.
                        {% endblocktrans %}</p>
                        <div class="text-center" style="margin-top: 40px;">
                            <div><i class="fas fa-3x fa-sync-alt fa-spin"></i><div class="text-bold pt-2">{% trans 'Setting up' %}...</div></div>
                        </div>
                    </div>

                </div>
                <div class="progress" style="height: 2px;">
                      <div id="progress_bar" class="progress-bar bg-orange" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer text-sm" id="status_bar">
                    {% trans 'Status' %}: {% trans 'Initializing' %}...
                </div>
                <!-- /.card-footer-->
            </div>
            <!-- /.card -->
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ block.super }}
<script>
$(() => {
    const path = 'wss://' + window.location.host + '/ws/commander/begin_setup/';
    const statusSocket = new WebSocket(path);

    statusSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        console.log(data.message);
        console.log(data.server_code);
        $('#progress_bar').attr('aria-valuenow', data.progress_value);
        $('#progress_bar').attr('style', 'width:' + data.progress_value + '%;');
        if (data.message == 'DONE') {
            setTimeout(() => {$(location).attr('href', '/?new=1');}, 1500);
        } else {
            $('#status_bar').html(data.message);
        }
    }

    statusSocket.onclose = function (e) {
        console.log(e.data);
        console.log('disconnected');
       // alert('unexpected disconnect');
       // $(location).attr('href', '/');
    }

    statusSocket.onopen = function (e) {
        console.log('opening websocket')
        console.log('sending message')
        statusSocket.send(JSON.stringify({
                'message': 'start-setup'
            }));
    }
});

</script>
{% endblock %}

edscc/templates/commander/statistics.html
{% load i18n %}
{% load humanize %}
{% load formatting %}
{% for category, data in statistics.items %}
    {% if category not in tags_ignored %}
        <div class="card">
            <div class="card-header">
                <h3 class="card-title text-orange">{% trans category|to_space %}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover table-sm table-striped text-nowrap">
                    <thead>
                    <tr>
                        <th style="width: 80%;">{% trans 'Description' %}</th>
                        <th class="text-right" style="width: 20%;">{% trans 'Value' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for label, value in data.items %}
                        <tr>
                            <td>{% trans label|to_space %}</td>
                            <td class="text-right">{{ value|intcomma }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    {% endif %}
{% endfor %}