config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from edscc.core.views import (
    galnet_news,
    galnet_news_detail,
    home_page,
    login_required_alert,
    placeholder,
    privacy_policy,
    sync_galnet_news,
    install_setup,
)
from edscc.commander import urls as commander_urls
from edscc.squadron import urls as squadron_urls

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path("admin/sync/galnet_news/", sync_galnet_news, name="sync-galnet-news"),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", home_page, name="home"),
    path("install-setup/", install_setup, name="install-setup"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("galnet/", galnet_news, name="galnet"),
    path("galnet/<slug:slug>", galnet_news_detail, name="galnet-detail"),
    path("blog/", placeholder, name="blog"),
    path("github/", placeholder, name="github"),
    path("patreon/", placeholder, name="patreon"),
    path("discord/", placeholder, name="discord"),
    path("placeholder/", placeholder, name="placeholder"),
    path("privacy_policy/", privacy_policy, name="privacy-policy"),
    path("commander/", include(commander_urls, namespace="commander")),
    path("squadron/", include(squadron_urls, namespace="squadron")),
    path("login_required/", login_required_alert, name="login-required"),
    path("martor/", include("martor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("edscc.api.urls")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

edscc/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"groups", views.GroupViewSet)
# router.register(r'commander', views.CommanderViewSet)


# Wire up API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    path("", include(router.urls)),
    path("commander/<int:pk>", views.commander_detail, name="commander_detail"),
    path("auth/", include("rest_framework.urls", namespace="rest_framework")),
]

edscc/commander/urls.py
from django.urls import path

from edscc.core.views import placeholder, cmdr_fleet_carrier, sync_fleet_carrier

from .views import (
    about_commander,
    dashboard,
    game_journal,
    game_journal_upload,
    initial_setup,
    activities_report,
    chart_js_generator,
)
from .chart_views import CommanderDashboardLineChart, CommanderDashboardPieChart
from .ajax_datatables import AjaxJournalLog

app_name = "commander"

urlpatterns = [
    path(
        "datatable/report/commander/<slug:report>/",
        activities_report,
        name="ajax_activities_report",
    ),
    path("activities_report/", activities_report, name="activities_report"),
    path(
        "chart/line/<slug:report_id>/",
        CommanderDashboardLineChart.as_view(),
        name="commander_line_chart",
    ),
    path(
        "chart/pie/<slug:report_id>/",
        CommanderDashboardPieChart.as_view(),
        name="commander_pie_chart",
    ),
    path(
        "chart/js/<slug:report_id>/chart.js",
        chart_js_generator,
        name="chart_js_generator",
    ),
    path("dashboard/", dashboard, name="dashboard"),
    path("datatable/journal_log", AjaxJournalLog.as_view(), name="ajax_journal_log"),
    path("fleet_carrier/", cmdr_fleet_carrier, name="fleet_carrier"),
    path("game_journal/", game_journal, name="game_journal"),
    path("game_journal/upload/", game_journal_upload, name="game_journal_upload"),
    path("initial_setup/", initial_setup, name="initial_setup"),
    path("profile/", about_commander, name="profile"),
    path("sync_fleet_carrier/", sync_fleet_carrier, name="sync_fleet_carrier"),
]

edscc/squadron/urls.py
from django.urls import path

from edscc.core.views import placeholder, cmdr_fleet_carrier, sync_fleet_carrier

from .views import (
    join_squadron,
    setup_squadron,
    finish_activate_squadron,
    settings,
    roster,
    leaderboard,
)

from .ajax_datatables import AjaxMemberRoster

app_name = "squadron"

urlpatterns = [
    path("join_squadron/", join_squadron, name="join_squadron"),
    path("setup_squadron/", setup_squadron, name="setup_squadron"),
    path(
        "finish_activate_squadron/",
        finish_activate_squadron,
        name="finish_activate_squadron",
    ),
    path("settings/", settings, name="settings"),
    path("roster/", roster, name="roster"),
    path("datatable/roster/", AjaxMemberRoster.as_view(), name="roster_datatable"),
    path("leaderboard/", leaderboard, name="leaderboard"),
]

edscc/api/models.py
# from django.db import models

# Create your models here.

edscc/squadron/models.py
import uuid as uuid
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Faction(models.Model):
    name = models.CharField(max_length=255)
    logo = models.CharField(max_length=255, blank=True, null=True)
    journal_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "faction"


class Power(models.Model):
    name = models.CharField(max_length=255)
    logo = models.CharField(max_length=255, blank=True, null=True)
    journal_id = models.IntegerField(blank=True, null=True)
    color_power = models.CharField(max_length=7, blank=True, null=True)

    class Meta:
        managed = True
        db_table = "power"


class Rank(models.Model):
    group_code = models.CharField(max_length=20, blank=True, null=True)
    assigned_id = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=20)
    perm_mask = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = "rank"


class Tags(models.Model):
    fdev_id = models.IntegerField()
    collection = models.CharField(max_length=25)
    name = models.CharField(max_length=40)
    badge_color = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        indexes = [models.Index(fields=["fdev_id"])]
        managed = True
        db_table = "tags"


class MinorFaction(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    player_faction = models.BooleanField(default=False)
    eddb_id = models.IntegerField(blank=True, null=True, db_index=True)

    class Meta:
        managed = True
        db_table = "minor_faction"


class Squadron(models.Model):
    ENGLISH = "en"
    FRENCH = "fr"
    GERMAN = "de"
    PORTUGUESE = "pt"
    RUSSIAN = "ru"
    SPANISH = "es"

    LANGUAGE_CHOICES = [
        (ENGLISH, _("English")),
        (FRENCH, _("French")),
        (GERMAN, _("German")),
        (PORTUGUESE, _("Portuguese")),
        (RUSSIAN, _("Russian")),
        (SPANISH, _("Spanish")),
    ]

    PC = "PC"
    PS4 = "PS4"
    XBOX = "XBOX"

    PLATFORM_CHOICES = [
        (PC, _("PC")),
        (PS4, _("Playstation")),
        (XBOX, _("XBox")),
    ]

    uuid = models.UUIDField(db_index=True, default=uuid.uuid4)
    fdev_id = models.IntegerField()
    name = models.CharField(max_length=255)
    tag = models.CharField(max_length=4, blank=True, null=True)
    owner_id = models.IntegerField()
    owner_name = models.CharField(max_length=50)
    active = models.BooleanField(default=True)
    platform = models.CharField(max_length=4, choices=PLATFORM_CHOICES, default=PC)
    primary_language = models.CharField(
        max_length=2, choices=LANGUAGE_CHOICES, default=ENGLISH
    )
    accept_new_members = models.BooleanField(default=True)
    admin = models.OneToOneField(User, models.CASCADE)
    superpower = models.ForeignKey(Faction, models.CASCADE, blank=True, null=True)
    faction = models.ForeignKey(MinorFaction, models.CASCADE, blank=True, null=True)
    power = models.ForeignKey(Power, models.CASCADE, blank=True, null=True)
    home_base = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    welcome_message = models.TextField(blank=True, null=True)
    require_approval = models.BooleanField(default=True)
    invite_link = models.BooleanField(default=False)
    squadron_tags = models.ManyToManyField(Tags, blank=True)
    established_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = True
        db_table = "squadron"


# class SquadronTags(models.Model):
#     squadron = models.ForeignKey(Squadron, models.CASCADE)
#     tag = models.ForeignKey("Tags", models.CASCADE)
#
#     class Meta:
#         managed = True
#         db_table = "squadron_tags"


class CustomRank(models.Model):
    squadron = models.ForeignKey(Squadron, models.CASCADE)
    order_id = models.SmallIntegerField()
    name = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = "custom_rank"


class SquadronRoster(models.Model):
    squadron = models.ForeignKey(Squadron, models.CASCADE)
    member_id = models.IntegerField(db_index=True)
    cmdr_name = models.CharField(max_length=100)
    has_account = models.BooleanField(default=False)
    is_member = models.BooleanField(default=True)
    rank = models.ForeignKey(
        Rank, models.CASCADE, related_name="squadron_rank", default=1, null=False
    )
    rank_combat = models.ForeignKey(
        Rank, models.CASCADE, related_name="rank_combat", default=6, null=False
    )
    rank_trade = models.ForeignKey(
        Rank, models.CASCADE, related_name="rank_trade", default=15, null=False
    )
    rank_explore = models.ForeignKey(
        Rank, models.CASCADE, related_name="rank_explore", default=24, null=False
    )
    rank_mercenary = models.ForeignKey(
        Rank, models.CASCADE, related_name="rank_mercenary", default=72, null=False
    )
    rank_exobiologist = models.ForeignKey(
        Rank, models.CASCADE, related_name="rank_exobiologist", default=81, null=False
    )
    join_date = models.DateTimeField()
    request_date = models.DateTimeField()
    last_online = models.DateTimeField()
    leave_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = "squadron_roster"


class Leaderboard(models.Model):
    squadron = models.ForeignKey(Squadron, models.CASCADE)
    platform = models.CharField(max_length=4, db_index=True)
    leaderboard_type = models.CharField(max_length=12, db_index=True)
    content = models.JSONField()
    last_updated = models.DateField(auto_now_add=True, db_index=True)

    class Meta:
        managed = True
        db_table = "leaderboard"

edscc/commander/forms.py
from django import forms

from .models import JournalLog


class JournalLogForm(forms.ModelForm):
    class Meta:
        model = JournalLog
        fields = ("file",)

edscc/squadron/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Squadron


class SquadronForm(forms.ModelForm):

    home_base = forms.CharField(
        max_length=50,
        label=_("Home Base"),
        help_text=_(
            "Location of Squadron's home base, include the System and base name. (e.g. Sol - Abraham Lincoln)"
        ),
    )

    primary_language = forms.ChoiceField(
        label=_("Primary Language"),
        choices=Squadron.LANGUAGE_CHOICES,
        required=True,
        help_text=_(
            "Primary language of this Squadron used for announcements, messaging, etc."
        ),
    )

    description = forms.CharField(
        label=_("Description"),
        widget=forms.Textarea(attrs={"rows": 4}),
        help_text=_("Write short description about your Squadron"),
        required=False,
    )

    welcome_message = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4}),
        help_text=_(
            "The welcome message will be shown to commanders after logging in the system for the first time. (Use Markdown for formatting)"
        ),
        required=False,
    )

    require_approval = forms.BooleanField(
        label=_(
            "Require approval from squad leaders to associate their accounts to this Squadron on ED:SCC"
        )
    )

    uuid = forms.UUIDField(
        widget=forms.HiddenInput(),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = "squadron_form"
        self.helper.form_class = "form-text"
        self.helper.form_method = "post"
        # self.helper.layout = Layout(
        #     Field("uuid", type="hidden"),
        # )

    class Meta:
        model = Squadron
        fields = (
            "home_base",
            "primary_language",
            "description",
            "welcome_message",
            "require_approval",
            "uuid",
        )

edscc/api/views.py
import logging

from django.contrib.auth.models import Group, User
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from edscc.commander.models import Commander

from .serializers import GroupSerializer, UserSerializer

# Create your views here.

log = logging.getLogger(__name__)


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """

    queryset = User.objects.all().order_by("-date_joined")
    serializer_class = UserSerializer
    permission_classes = (IsAuthenticated,)


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """

    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = (IsAuthenticated,)


# class CommanderViewSet(viewsets.ModelViewSet):
#     queryset = Commander.objects.all()
#     serializer_class = CommanderSerializer
#     permission_classes = [IsAuthenticated]


@api_view(["GET"])
def commander_detail(request, pk):
    log.debug(request.user)
    log.debug(request.auth)

    content = {"commander": JSONRenderer().render(Commander.objects.filter(user_id=pk))}
    return Response(content)


# class HelloView(APIView):
#     permission_classes = [IsAuthenticated]
#
#     def get(self, request):
#         log.debug(request.user)
#         log.debug(request.auth)
#         content = {
#             'message': 'Hello world!'
#         }
#         return Response(content)

edscc/templates/squadron/activation_next_step.html
{% extends 'base.html' %}
{% load i18n static humanize formatting crispy_forms_tags %}
{% block content %}
    <div class="container-fluid pl-3 pr-3">
        <div class="row">
            <div class="col-md-12" style="overflow: hidden;">
                <div>
                    <img src="{% static 'img/squadron_header.png' %}" style=" width: 100%; object-fit: contain;" alt="Squadron">
                    <div class="fc-name">
                        <span class="text-orange h3 text-bold">{% trans 'Squadron Activated' %}</span><br>
                        <span class="text-white text-sm"></span>
                    </div>
                    <div class="fc-access text-right">
                    </div>
                    <div class="fc-footer-left p-2" style="background-color: rgba(0,0,0,0.6);">
                        {% trans 'Your Squadron has been activated on ED:SCC. Please follow directions below to complete the setup.' %}
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-4">
                <div class="row">
                    <div class="card card-secondary shadow">
                        <div class="card-header">
                            <h3 class="card-title text-lg pt-1">{{ squadron.name }}
                                <span class="text-sm text-muted">{{ squadron.tag }}</span></h3>
                            <div class="card-tools float-right m-1">
                                <div class="text-success text-md p-0 m-0">
                                    <i class="fas fa-desktop mr-2"></i>PC
                                </div>
                            </div>
                        </div>
                        <div class="card-body table-responsive overflow-hidden">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-4 pl-2">
                                        {% if logo %}
                                            <img class="profile-squadron-img" src="{% get_static_prefix %}img/ed-assets/thumbnails/{{ logo }}" alt="Faction Power Logo">
                                        {% else %}
                                            <div style="height: 120px" class="text-center">
                                                <i class="fas fa-question fa-7x text-secondary"></i></div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-8">
                                        <span class="text-orange"><i class="fas fa-tag mr-2"></i>Tags</span>
                                        <p class="text-muted">
                                            {% for tag in squadron.squadron_tags.all %}
                                                <span class="badge badge-pill {{ tag.badge_color }}">{{ tag.name }}</span>
                                            {% endfor %}
                                        </p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 mt-3">
                                        <span class="text-orange"><i class="fas fa-info-circle mr-2"></i>Information</span>
                                        <table class="table table-sm table-borderless text-nowrap">
                                            <tbody>
                                            <tr>
                                                <td style="width: 50%">{% trans 'Owner' %}</td>
                                                <td style="width: 50%">{{ owner.user.name|default:"Not on ED:SCC" }}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Administrator' %}</td>
                                                <td>{% trans 'CMDR' %} {{ admin.commander_name }}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Number of Members' %}</td>
                                                <td>{{ num_members|intcomma }}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Superpower' %}</td>
                                                <td>{% trans squadron.superpower.name|default:"None" %}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Power' %}</td>
                                                <td>{% trans squadron.power.name|default:"None" %}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Faction' %}</td>
                                                <td>{{ squadron.faction.name }}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Primary Language' %}</td>
                                                <td>{% trans squadron.get_primary_language_display %}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Accepting New Members' %}</td>
                                                <td>{% if squadron.accept_new_members %}{% trans 'Yes' %}{% else %}
                                                    {% trans 'No' %}{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Approval Required' %}</td>
                                                <td>{% if squadron.require_approval %}{% trans 'Yes' %}{% else %}
                                                    {% trans 'No' %}{% endif %}</td>
                                            </tr>
                                            <tr>
                                                <td>{% trans 'Established on' %}</td>
                                                <td>{{ squadron.established_on|date:"DATETIME_FORMAT" }}</td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8" style="overflow: hidden;">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title text-lg pt-1"><i class="fas fa-cogs mr-2"></i>{% trans 'Additional Information' %}</h3>
                        <div class="card-tools">
                            <button id="finish_setup" class="btn btn-outline-success btn-sm">
                                <i class="fas fa-save mr-2"></i>{% trans 'Finish Setup' %}
                            </button>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        {% crispy squadron_form squadron_form.helper %}
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->


            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(() => {
            $('#finish_setup').click(function (e) {
                $('#squadron_form').submit();
            });
        });
    </script>
{% endblock %}

edscc/templates/squadron/leaderboard.html
{% extends 'base.html' %}
{% load i18n gravatar account humanize static formatting %}
{% get_current_language as LANGUAGE_CODE %}
{% block content %}
    <div class="container-fluid">
        <div class="row ml-1">
            <div class="col-md-12">
                <div class="card shadow card-secondary">
                    <h5 class="card-header">
                        <i class="ed-asset ed-asset-icon-leaderboard_website mr-2"></i>{% trans 'Squadron Leaderboard' %}
                    </h5>
                </div>
            </div>
        </div>
        <div class="row ml-1">
            <div class="col-md-12">
                <div class="row">
                    {% for row in leaderboards %}
                        {% if forloop.counter0|divisibleby:3 %}
                            {% if forloop.counter0 %}</div>
                                <div class="row">{% endif %}
                        {% endif %}
                        <div class="col-md-4">
                            <div class="card shadow">
                                <h5 class="card-header">
                                    <i class="{{ row.icon }} mr-2"></i>{% trans row.type|title %}
                                </h5>
                                <div class="card-body">
                                    <table class="table table-sm table-striped table-hover table-dark">
                                        <thead>
                                        <tr>
                                            <th scope="col" style="width: 70px;">#</th>
                                            <th scope="col">{% trans 'Squadron' %}</th>
                                            <th scope="col" class="text-right" style="width: 100px;">
                                                {% trans 'Score' %}
                                            </th>
                                            <th scope="col" class="text-right" style="width: 50px;">Change</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in row.board %}
                                            <tr
                                                    {% if i.squadron == fdev_id %} class="text-orange text-bold"{% endif %}>
                                                <th scope="row">{{ i.rank|add:"1" }} {% if i.delta_rank %}{% if i.delta_rank > 0 %}<span class="text-xs ml-1 text-success"><i class="fas fa-chevron-up">{% else %}<span class="text-xs ml-1 text-danger"><i class="fas fa-chevron-down">{% endif %}</i> {{ i.delta_rank|abs|floatformat }}</span>{% endif %}</th>
                                                <td>{{ i.name }}</td>
                                                <td class="text-right">{{ i.score|intcomma }}</td>
                                                <td class="text-right">{% if i.delta_score %}{{ i.delta_score|floatformat:"1" }}%{% endif %}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

edscc/templates/squadron/roster.html
{% extends 'base.html' %}
{% load i18n gravatar account humanize static %}
{% block css %}
    {{ block.super }}
    {#    <link rel="stylesheet" href="{% static 'ajax_datatable/css/style.css' %}">#}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <span class="h5">
                            <i class="fas fa-user-astronaut mr-1"></i>
                            {% trans 'Squadron Roster' %}
                        </span>
                    </div>
                    <div class="card-body pt-0">
                        <div class="table-responsive">
                            <table id="datatable" class="table table-sm table-dark table-striped table-hover table-condensed nowrap" style="width: 100%"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(() => {
            AjaxDatatableViewUtils.initialize_table(
                $('#datatable'),
                "{% url 'squadron:roster_datatable' %}",
                {
                    processing: true,
                    serverSide: true,
                    autoWidth: false,
                    scrollX: false,
                    dom: "<'row'<'col-sm-3'i>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-3'l><'col-sm-9'p>>",
                    language: {
                        search: '_INPUT_',
                        searchPlaceholder: '{% trans "Search..." %}',
                        info: "{% trans "datatable_info" %}",
                        infoEmpty: "{% trans "datatable_info_empty" %}",
                        infoFiltered: "{% trans "datatable_info_filtered" %}",
                        zeroRecords: "{% trans "datatable_zero_records" %}",
                        emptyTable: "{% trans "datatable_empty_table" %}",
                        paginate: {
                            first: '&laquo;',
                            previous: '&lsaquo;',
                            next: '&rsaquo;',
                            last: '&raquo;'
                        }
                    },
                    initComplete: function () {
                        $('.dataTables_filter input[type="search"]').css({
                            width: '200px', display: 'inline-block'
                        });
                    },
                    drawCallback: function () {
                        $('.dataTables_paginate > .pagination').addClass('pagination-sm');
                    }
                }, {
                    uuid: '{{ squadron_info.uuid }}',
                },
            );
        });
    </script>
{% endblock %}